services:
  - type: web
    name: memorial-metrics
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ODOO_URL
        sync: false
      - key: ODOO_DB
        sync: false
      - key: ODOO_USERNAME
        sync: false
      - key: ODOO_PASSWORD
        sync: false
